import { expect, test } from 'vitest'
import { ContextFreeGrammar } from '../../../wasm/index.js'

test('example-1', () => {
    const cfg = new ContextFreeGrammar()
    cfg.parse("E -> T E'  T -> F T'  E' -> + T E' | ε  T' -> * F T' | ε  F -> ( E ) | id")
    const result = cfg.computeFirstAndFollowSet()
    expect(result.size()).toBe(5)
    expect(result.symbolAt(0)).toBe("E")
    expect(result.symbolAt(1)).toBe("T")
    expect(result.symbolAt(2)).toBe("E'")
    expect(result.symbolAt(3)).toBe("T'")
    expect(result.symbolAt(4)).toBe("F")
    expect(result.getFirstSet("E")).toStrictEqual(["(", "id"])
    expect(result.getFirstSet("T")).toStrictEqual(["(", "id"])
    expect(result.getFirstSet("E'")).toStrictEqual(["+", "ε"])
    expect(result.getFirstSet("T'")).toStrictEqual(["*", "ε"])
    expect(result.getFirstSet("F")).toStrictEqual(["(", "id"])
    expect(result.getFollowSet("E")).toStrictEqual([")", "¥"])
    expect(result.getFollowSet("T")).toStrictEqual([")", "+", "¥"])
    expect(result.getFollowSet("E'")).toStrictEqual([")", "¥"])
    expect(result.getFollowSet("T'")).toStrictEqual([")", "+", "¥"])
    expect(result.getFollowSet("F")).toStrictEqual([")", "*", "+", "¥"])
})

test('example-2', () => {
    const cfg = new ContextFreeGrammar()
    cfg.parse("S -> A B C  A -> a | ε  B -> b | ε  C -> c")
    const result = cfg.computeFirstAndFollowSet()
    expect(result.size()).toBe(4)
    expect(result.symbolAt(0)).toBe("S")
    expect(result.symbolAt(1)).toBe("A")
    expect(result.symbolAt(2)).toBe("B")
    expect(result.symbolAt(3)).toBe("C")
    expect(result.getFirstSet("S")).toStrictEqual(["a", "b", "c"])
    expect(result.getFirstSet("A")).toStrictEqual(["a", "ε"])
    expect(result.getFirstSet("B")).toStrictEqual(["b", "ε"])
    expect(result.getFirstSet("C")).toStrictEqual(["c"])
    expect(result.getFollowSet("S")).toStrictEqual(["¥"])
    expect(result.getFollowSet("A")).toStrictEqual(["b", "c"])
    expect(result.getFollowSet("B")).toStrictEqual(["c"])
    expect(result.getFollowSet("C")).toStrictEqual(["¥"])
})
